development:
  adapter: postgres
  encoding: utf8
  database: stripstarter
  pool: 5
  username: stripstarter
  password: YOUR_PASSWORD_HERE

production:
  adapter: postgres
  encoding: utf8
  database: stripstarter
  pool: 5
  username: stripstarter
  password: YOUR_PASSWORD_HERE

test:
  adapter: postgres
  encoding: utf8
  database: stripstarter_test
  pool: 5
  username: stripstarter
  password: YOUR_PASSWORD_HERE